---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/build/networking_ebpf"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/build/networking"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/build/storage"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/build/storage/tests/it/test-drivers"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/build/storage/tests/it/traffic-generator"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/build/storage/spdk/docker/spdk-app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/build/storage/spdk/docker/traffic-generator"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/build/storage/spdk/docker/build_base"
    schedule:
      interval: "weekly"
